version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password

  backend:
    build:
      context: ./back
    command: gunicorn Dinamo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
    env_file:
      - ./back/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./front
    ports:
      - "80:80"

volumes:
  postgres_data: