# Generated by Django 5.0.4 on 2024-04-30 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAuto', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(default=None, max_length=50)),
                ('color', models.CharField(default=None, max_length=50)),
                ('precio', models.BigIntegerField()),
                ('año', models.IntegerField()),
                ('descripcion', models.CharField(default=None, max_length=150)),
                ('foto', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSede', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Sede',
            },
        ),
        migrations.CreateModel(
            name='AutoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAuto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='idAuto_AutoSede', to='Carapp.auto')),
                ('idSede', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='idSede_AutoSede', to='Carapp.sede')),
            ],
            options={
                'db_table': 'AutoSede',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='idRol_UsuarioRol', to='Carapp.rol')),
                ('idUsuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='idUsuario_UsuarioRol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsuarioRol',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSede', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='idSede_UsuarioSede', to='Carapp.sede')),
                ('idUsuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='idUsuario_UsuarioSede', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsuarioSede',
            },
        ),
    ]
