name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./back
        push: true
        tags: javierdiaz01/backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./front
        push: true
        tags: javierdiaz01/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Authenticate to Google Cloud
     # uses: google-github-actions/auth@v1
      #with:
       # credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    #- name: Configure gcloud
     # run: |
      #  gcloud config set project ${{ secrets.GKE_PROJECT }}
       # gcloud config set compute/zone ${{ secrets.GKE_ZONE }}
        #gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/