name: Django Tests

on:
  push:
    branches: [ main ]  # Ejecutar las pruebas cuando se hace push a la rama principal
  pull_request:
    branches: [ main ]  # Ejecutar las pruebas cuando se abre un pull request hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      run: |
        python manage.py test
